### ISSUE TITLE
circleCI + unit tests

### ISSUE THREAD

**Issue by dbekaert** [isce-framework/fringe#15]
Will work on a CircleCI to test the build.
If you have unit tests they could be added post build to verify PRs

https://github.com/dbekaert/fringe/blob/circleCI/.circleci/config.yml

**Comment by hfattahi** [comment]
That will be a great.

**Comment by dbekaert** [comment]
@hfattahi @piyushrpt the isce dependency does it needs the stack setup too or just internals?

**Comment by piyushrpt** [comment]
It only needs the internals for now.

**Comment by dbekaert** [comment]
@hfattahi @piyushrpt Do you have a few unit test or basic calls that would be good to verify code?

**Comment by dbekaert** [comment]
Looks like its integrated under PR #22
