### ISSUE TITLE
Undefined symbol: omp_get_thread_num

### ISSUE THREAD

**Issue by stoormgeo** [isce-framework/fringe#3]
Hi, 
I tried to estimate wrapped phase time-series (DS) with sequential.py and got the error with 
omp_get_thread_num. 

writing  /home/insar/slc/Sequential/miniStacks/20170201_20170520/stack/stack.vrt
-1 True
0 True
1 True
2 True
3 True
4 True
5 True
6 True
7 True
8 True
9 True
Traceback (most recent call last):
  File "/opt/fringe/bin/sequential.py", line 199, in <module>
    runEvd(inps, miniStack.stackVRT, weightDS, outDir, miniStackCount, compSlcDir, compressedSlcName)
  File "/opt/fringe/bin/sequential.py", line 52, in runEvd
    import evdlib
ImportError: /opt/fringe/python/evdlib.so: undefined symbol: omp_get_thread_num

**Comment by piyushrpt** [comment]
Could you try the changes to src/evd/CMakelists.txt file in #4

**Comment by stoormgeo** [comment]
Ok, issue is fix.
Thx
