### ISSUE TITLE
Output interferogram clarification

### ISSUE THREAD

**Issue by 4restwilliams** [isce-framework/fringe#30]
Do the output deformation interferograms of FRInGE represent the cumulative deformation of the full stack, (i.e. date1_date2, date1_date3, date1_date4, ...), or deformation between successive pairs (i.e. date1_date2, date2_date3, date3_date4, ...)? This is relevant when importing results into MintPy. Thanks!

**Comment by piyushrpt** [comment]
They represent cumulative deformation (wrapped)

**Comment by 4restwilliams** [comment]
Thank you!
