### ISSUE TITLE
building stopped with something related with  libarmadillo-dev ? 

### ISSUE THREAD

**Issue by JianbaoSun** [isce-framework/fringe#31]
Hi, guys, thanks for the new code!
I have a try with the Fringe code today.  My compiling and building stopped at the Fit function. 
It seems a problem of libarmadillo-dev, which I installed with apt-get under ubuntu with anaconda3.  
Please see the following screen report. Any suggestions? thanks! 

#######################
[67%] Building CXX object src/fit/CMakeFiles/fit.dir/Fit.cc.o
/home/sun/FRINGE/src/fringe/src/fit/Fit.cc: In member function ‘virtual void Fit::estimate_Tau(str)’:
/home/sun/FRINGE/src/fringe/src/fit/Fit.cc:589:30: error: ‘index_min’ is not a member of ‘arma’
      arma::urowvec idx_min = arma::index_min(rmse_vs_tau); 
                              ^
src/fit/CMakeFiles/fit.dir/build.make:81: recipe for target 'src/fit/CMakeFiles/fit.dir/Fit.cc.o' failed
make[2]: *** [src/fit/CMakeFiles/fit.dir/Fit.cc.o] Error 1
CMakeFiles/Makefile2:506: recipe for target 'src/fit/CMakeFiles/fit.dir/all' failed
make[1]: *** [src/fit/CMakeFiles/fit.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rtburns-jpl** [comment]
What Ubuntu version are you on? I think arma::index_min requires Armadillo version 8.100. Could you check what version you have installed?
https://sourceforge.net/p/arma/news/2017/08/armadillo-c-linear-algebra-version-8100/

**Comment by JianbaoSun** [comment]
Thanks! That's great! I changed armadillo from v 6.5 to v 8.1. It works very well!
