### ISSUE TITLE
FRInGE to SNAPHU wrapped value translation

### ISSUE THREAD

**Issue by 4restwilliams** [isce-framework/fringe#33]
The wrapped deformation output of FRInGE has the value range **-pi** to **pi**, but [SNAPHU documentation](https://web.stanford.edu/group/radar/softwareandlinks/sw/snaphu/snaphu_man1.html) states that input interferogram values should range from **0** to **2pi**. Should FRInGE outputs be translated by **pi** before they are unwrapped using SNAPHU?

**Comment by yunjunz** [comment]
The range of [0, 2pi) should be used only if the input wrapped interferogram is not complex. fringe uses complex format as the input for SNAPHU, so the current format is correct.

**Comment by 4restwilliams** [comment]
Thank you for the explanation @yunjunz !
