### ISSUE TITLE
ERROR 1: Image file is too small

### ISSUE THREAD

**Issue by DONGYUSEN** [isce-framework/fringe#35]
What cause this:

ERROR 1: Image file is too small

**Comment by piyushrpt** [comment]
Please provide more information as requested on versions of isce, gdal etc. There is no information in this ticket to respond meaningfully.

**Comment by DONGYUSEN** [comment]
> Please provide more information as requested on versions of isce, gdal etc. There is no information in this ticket to respond meaningfully.

stackSentinel.py -s ../org -d ../dem/demLat_N32_N34_Lon_E107_E110.dem -o /Volumes/MSWAP/S1_orbit -a ../aux -c 2 -n 2 -b '33.49 33.55 108.60 108.70' -z 1 -r 3 -e 0.7 -W slc

when i use the  -W slc, there is no error now!
