### ISSUE TITLE
Exiting with error code ....(109)

### ISSUE THREAD

**Issue by DONGYUSEN** [isce-framework/fringe#37]
evd.py  -i coreg_stack/slcs_base.vrt  -o Sequential -w KS2/nmap  -x 11 -y 5 
Input Dataset: coreg_stack/slcs_base.vrt
Weights Dataset: KS2/nmap
Output Folder Sequential
Output compressed SLC folder Sequential
Output compressed SLC compslc.bin
Window size: 11 5
Memsize: 4096 Mb 
Blocksize: 64 lines 
Minimum neighbors: 5
Mini-stack counter: 1
Decomposition method: MLE
Number of uint32 bytes for mask: 8
Number of rows  = 588
Number of cols  = 2166
Number of bands = 37
Number of bands mismatch for weights and window size 
Half window size x of wts is different from input. 
Exiting with error code ....(109)

**Comment by piyushrpt** [comment]
```
Half window size x of wts is different from input.
```
Please provide the correct input options

**Comment by DONGYUSEN** [comment]
thx,
