### ISSUE TITLE
Error in adjustMiniStacks.py after updating to new tops2vrt.py

### ISSUE THREAD

**Issue by bjmarfito** [isce-framework/fringe#48]
An error was generated after I've run the adjustMiniStacks.py as shown below.

`adjustMiniStacks.py -s stack -m Sequential/miniStacks/ -d Sequential/Datum_connection/ -M 15 -o adjusted_wrapped_DS                                   This is the Open Source version of ISCE.                                                                                Some of the workflows depend on a separate licensed package.                                                            To obtain the licensed package, please make a request for ISCE                                                          through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.                                               Alternatively, if you are a member, or can become a member of WinSAR                                                    you may be able to obtain access to a version of the licensed sofware at                                                https://winsar.unavco.org/software/isce                                                                                 /mnt/f/2020_Masbate/Sentinel-1/post-EQ_time-series/asc/fringe/Sequential/miniStacks/slcs_base_slcs_base                 ERROR 4: /mnt/f/2020_Masbate/Sentinel-1/post-EQ_time-series/asc/fringe/Sequential/miniStacks/slcs_base_slcs_base/EVD/slcs_base.slc: No such file or directory                                                                                   Traceback (most recent call last):                                                                                        File "/home/abscissa/fringe/install/bin/adjustMiniStacks.py", line 294, in <module>                                       adjust_wrapped(dateList, inps)                                                                                        File "/home/abscissa/fringe/install/bin/adjustMiniStacks.py", line 215, in adjust_wrapped                                 length, width = getSize(stackDict[dateList[0]][0])                                                                    File "/home/abscissa/fringe/install/bin/adjustMiniStacks.py", line 107, in getSize                                        length = ds.RasterYSize                                                                                             AttributeError: 'NoneType' object has no attribute 'RasterYSize' `

I've investigated and figured out that the error was possibly due to the updated tops2vrt.py which doesn't generate SLC VRTs from the ISCE2 topsStack processor.  The argument -c on the tops2vrt.py was removed which should produce these VRTs.

What is the possible workaround on this new issue?

**Comment by hfattahi** [comment]
Thnks @bjmarfito and sorry that we rushed merging https://github.com/isce-framework/fringe/pull/47. @vbrancat did you face similar issue during your processing?

**Comment by vbrancat** [comment]
No my error was a bit different. My plan was to merge the changes to the software all together to avoid any disruption. The easiest would be to revert the change to tops2vrt.py

**Comment by hfattahi** [comment]
Thanks @vbrancat for reverting the changes for now. @bjmarfito https://github.com/isce-framework/fringe/pull/49 should solve the issue for now.

**Comment by bjmarfito** [comment]
It works fine now. Thank you @vbrancat and @hfattahi!
