### ISSUE TITLE
despeck.py usage

### ISSUE THREAD

**Issue by stoormgeo** [isce-framework/fringe#55]
What is the best way to use despeck.py?
It gives an error then on startup. The same window sizes used.

`despeck.py -i /data/merged/fringe/coreg_stack/slcs_base.vrt -o /data/merged/fringe/Despeck/despeck -w /data/merged/fringe/KS2/count -l 100 -r 100000 -x 25 -y 35 -b 1`

Input Dataset: /data/insar/Proc/Specgeo/Marre/proc/merged/fringe/coreg_stack/slcs_base.vrt
Weights Dataset: /data/insar/Proc/Specgeo/Marre/proc/merged/fringe/KS2/count
Output Dataset: /data/insar/Proc/Specgeo/Marre/proc/merged/fringe/Despeck/despeck
Window size: 25 35
Memsize: 100000 Mb 
Blocksize: 100 lines 
Master band: 2
Number of uint32 bytes for mask: 114
Number of rows  = 4840
Number of cols  = 13909
Number of bands = 17
Number of bands mismatch for weights and window size 
Exiting with error code ....(108)

**Comment by piyushrpt** [comment]
The wts.hdr file should report what window sizes were used to generate it in the first place. You are providing it the count file, when it needs the wts file as input. This looks like  a mismatch in x and y arguments. And you are requesting 100GB of RAM with the memory option.

**Comment by stoormgeo** [comment]
> The wts/nmap.hdr file should report what window sizes were used to generate it in the first place. You are providing it the count file, when it needs the wts/nmap file as input. This looks like a mismatch in x and y arguments. And you are requesting 100GB of RAM with the memory option.

Thanks  Piyushrpt,
100 GB is fine, my machine can handle it. Window sizes are the same.
Tried putting nmap:

Input Dataset: /data/insar/Proc/Specgeo/Marre/proc/merged/fringe/coreg_stack/slcs_base.vrt
Weights Dataset: /data/insar/Proc/Specgeo/Marre/proc/merged/fringe/KS2/nmap
Output Dataset: /data/insar/Proc/Specgeo/Marre/proc/merged/fringe/Despeck/despeck
Window size: 25 35
ERROR 2: Too much memory needed
Memsize: 100000 Mb 
Blocksize: 100 lines 
Master band: 2
Number of uint32 bytes for mask: 114
Number of rows  = 4840
Number of cols  = 13909
Number of bands = 17
Could not open weights dataset {/data/insar/Proc/Specgeo/Marre/proc/merged/fringe/KS2/nmap}
Exiting with non-zero error code ... 105

**Comment by piyushrpt** [comment]
Those already use the despeck operation internally for all computations. This is just a utility to despeck a SAR image / individual interferogram using the neighborhood map - for visualization or other applications that build on it.

**Comment by stoormgeo** [comment]
> Those already use the despeck operation internally for all computations. This is just a utility to despeck a SAR image / individual interferogram using the neighborhood map - for visualization or other applications that build on it.

Ok. Thanks for guidance!
