### ISSUE TITLE
Make slc file from individual despeckled amplitude band and MLE phase

### ISSUE THREAD

**Issue by stoormgeo** [isce-framework/fringe#59]
Hi,
I'm looking a simple way to constract slc's (like files in /merged) from individual despeckled amplitude band and MLE phase for further PS-like analysis. 
So far I can't get a correct result with imageMath.py like:
`imageMath.py -e='a_0;b_0' --a="despeck_test;45772;float;1" --b="20180715.slc;45772;cfloat;1" -o test.slc -t cfloat`
Can you suggest any solution?
Thx

**Comment by piyushrpt** [comment]
You probably want `-e=a_0 * exp(J * b_0)`

**Comment by piyushrpt** [comment]
`gdal_calc.py` might give you more options related to formats and you wont need to specify dimensions manually either

**Comment by stoormgeo** [comment]
> You probably want `-e=a_0 * exp(J * b_0)`

Thanks Piyushrpt!
It looks like the right one.
