### ISSUE TITLE
Add Network.py and StackVRT.py to CMakeLists.txt

### ISSUE THREAD

**Issue by stoormgeo** [isce-framework/fringe#6]
Hi,
There are several modules missing from the build - Network.py and StackVRT.py.

**Comment by hfattahi** [comment]
Currently, none of them are getting used anywhere. Are you experiencing any issue due to these missing scripts?

**Comment by yunjunz** [comment]
Hi @hfattahi, the `Network` module is used in [integratePS.py#L17](https://github.com/isce-framework/fringe/blob/master/python/integratePS.py#L17), both of them are currently missing from the build and install/bin folder.

**Comment by hfattahi** [comment]
Thanks @yunjunz. Would you please confirm if  https://github.com/isce-framework/fringe/pull/11 solves this issue.

**Comment by yunjunz** [comment]
Hi @hfattahi, `integratePS.py` is also missing in the install directory, could you add that to the CMakeLists too?

**Comment by hfattahi** [comment]
Should be fixed by https://github.com/isce-framework/fringe/pull/12
