### ISSUE TITLE
Lack of spatial coherence

### ISSUE THREAD

**Issue by bjmarfito** [isce-framework/fringe#68]
Does FRInGE generate spatial coherence files since I noticed that it only generates one temporal coherence file?

**Comment by hfattahi** [comment]
No it does not generate traditional spatial coherence.

**Comment by bjmarfito** [comment]
Thank you @hfattahi for answering my question. I don't know if this is a naive question, why FRInGE does not generate it? Is the temporal coherence enough to determine the quality of outputs from FRInGE?

**Comment by piyushrpt** [comment]
`despeck` has an option to generate coherence with local neighborhood, but yes this is not your traditional box car /  fixed kernel based spatial coherence

**Comment by hfattahi** [comment]
The traditional spatial coherence is generated on the fly for all possible pairs, and they may be used during the phase series estimation (depending on the estimation method) but they are not written to disk. The temporal coherence is a good measure of the quality of the inversion and yes it can be used as a metric for the quality of the estimated wrapped interferograms. wherever the temporal coherence is low, you would see noisier phase. 

As Piyush pointed out, If you are looking for traditional coherence metric for some reason, you can form individual interferograms with despeck module. The only difference with the traditional coherence is that an adoptive window is used for multi-looking and coherence estimation. But that module won't give you a time-series. Only one single interferogram and its coherence.

**Comment by bjmarfito** [comment]
Thank you @hfattahi for the in-depth explanation. Yeah, will try the suggested `despeck` option by @piyushrpt.
