### ISSUE TITLE
process after estimating  the wrapped phase time-series for DS pixels using the full covariance matrix of the entire stack using the evd.py command

### ISSUE THREAD

**Issue by asteriospapas** [isce-framework/fringe#70]
Hello, 

Following the steps inside the FRInGE Workflows, I have successfully ran 
''
nmap.py -i coreg_stack/slcs_base.vrt -o KS2/nmap -c KS2/count -x 11 -y 5;
evd.py -i coreg_stack/slcs_base.vrt -w KS2/nmap -o EVD -x 11 -y 5 -n 20;
ampdispersion.py -i coreg_stack/slcs_base.vrt -o ampDispersion/ampdispersion -m ampDispersion/mean;
gdal2isce_xml.py -i ampDispersion/ampdispersion;
gdal2isce_xml.py -i ampDispersion/mean;
imageMath.py -e="a<0.4" --a=ampDispersion/ampdispersion  -o ampDispersion/ps_pixels -t byte;
''
However when I run the next step shown in the workflows, which is integratePS.py,
'' integratePS.py -s coreg_stack/slcs_base.vrt -d EVD/ -t EVD/tcorr.bin -p ampDispersion/ps_pixels -o PS_DS --unwrap_method snaphu;''
the following error comes up:
ERROR 4: EVD/20190802.slc.vrt: No such file or directory
ERROR 4: EVD/20190814.slc.vrt: No such file or directory
Traceback (most recent call last):
  File "/home/tools/src/fringe/install/bin/integratePS.py", line 295, in <module>
    main()
  File "/home/tools/src/fringe/install/bin/integratePS.py", line 253, in main
    integratePS2DS(dsDS_band_i, dsDS_band_j, dsSlc, dsTcor, psDataset, outDataset,
  File "/home/tools/src/fringe/install/bin/integratePS.py", line 98, in integratePS2DS
    nrows = dsDS_band_i.RasterYSize
AttributeError: 'NoneType' object has no attribute 'RasterYSize'

I understand that when you run the ministack version, ex.:
''sequential.py -i ../merged/SLC -s 5 -m 20 -o Sequential -w KS2/nmap -b coreg_stack/slcs_base.vrt -x 11 -y 5;
adjustMiniStacks.py -s slcs/ -m Sequential/miniStacks/ -d Sequential/Datum_connection/ -M 5 -o adjusted_wrapped_DS;''
the adjusted_wrapped_DS contains the .vrt files. However just by running the evd.py, as proposed in the workflow, they are not produced, to continue the integration with the PS. 

Am I missing a step or is there an issue?

Thank you

**Comment by scottstanie** [comment]
Hi, thanks for pointing out this inconsistency between the workflows. Seems like they should either put out the same files, or the search for `.slc.vrt` files shouldn't be hardcoded into the "intergrate" script. I'll take a look and see if there's a quick fix.
